"use client";

import { useRef, useState } from "react";
import * as XLSX from "xlsx";
import { Activity, ArrowDownToLine, Check, ChevronRight, Download, FileSpreadsheet, Languages, LockKeyhole, ShieldCheck, Sparkles, UploadCloud } from "lucide-react";

type Lang = "es" | "en" | "pt";
type Result = { patient: string; date: string; intake: number; output: number; balance: number; urine: number; records: number; bands: { label: string; intake: number; output: number; balance: number }[] };

const copy = {
  es: { navHow:"Cómo funciona", navBenefits:"Beneficios", navSafety:"Seguridad", badge:"Balance hídrico, claro y confiable", titleA:"Menos cálculo.", titleB:"Más tiempo para cuidar.", intro:"Descarga la plantilla, registra ingresos y egresos y súbela aquí. La app organiza el balance, detecta inconsistencias y prepara un informe listo para descargar.", template:"Descargar plantilla Excel", start:"Analizar mi plantilla", privacy:"Procesamiento local · Tus datos no salen de este dispositivo", step:"Flujo de trabajo", s1:"Descarga", s1d:"Plantilla clara, con listas y fórmulas protegidas visualmente.", s2:"Registra", s2d:"Completa los datos del paciente y cada movimiento en mL.", s3:"Analiza", s3d:"Sube el archivo y obtén totales, tendencias y explicaciones.", upload:"Sube la plantilla completada", drop:"Arrastra tu archivo Excel aquí", browse:"o selecciónalo desde tu equipo", choose:"Seleccionar archivo", only:".xlsx · máximo recomendado 10 MB", ready:"Análisis listo", patient:"Paciente", intake:"Ingresos", output:"Egresos", net:"Balance neto", urine:"Diuresis", interpretation:"Interpretación orientativa", positive:"El balance es positivo: los ingresos superan los egresos. Correlaciona este resultado con la valoración clínica, el peso, las pérdidas y la prescripción.", negative:"El balance es negativo: los egresos superan los ingresos. Revisa la tendencia y correlaciona con el estado clínico y el protocolo institucional.", neutral:"El balance es neutro: ingresos y egresos son equivalentes en el período registrado.", export:"Descargar balance terminado", trend:"Balance por franja horaria", demo:"Vista previa con datos de ejemplo", safeTitle:"Diseñada para el trabajo real de enfermería", safeText:"Campos guiados, unidades visibles, controles de consistencia y una lectura rápida para el cambio de turno.", guard1:"Cálculos auditables", guard2:"Sin almacenamiento de pacientes", guard3:"Trilingüe", note:"Herramienta de apoyo. Verifica los datos originales y sigue el protocolo institucional; no sustituye el juicio clínico.", error:"No pude reconocer la plantilla. Usa la plantilla oficial y conserva los nombres de sus hojas.", uploaded:"Archivo analizado correctamente", records:"registros" },
  en: { navHow:"How it works", navBenefits:"Benefits", navSafety:"Safety", badge:"Clear, reliable fluid balance", titleA:"Less calculation.", titleB:"More time to care.", intro:"Download the template, record intake and output, then upload it here. The app organizes the balance, detects inconsistencies and prepares a finished report.", template:"Download Excel template", start:"Analyze my template", privacy:"Local processing · Your data never leaves this device", step:"Workflow", s1:"Download", s1d:"A clear template with lists and visually protected formulas.", s2:"Record", s2d:"Complete patient data and every movement in mL.", s3:"Analyze", s3d:"Upload the file for totals, trends and clear explanations.", upload:"Upload the completed template", drop:"Drop your Excel file here", browse:"or select it from your computer", choose:"Choose file", only:".xlsx · recommended maximum 10 MB", ready:"Analysis ready", patient:"Patient", intake:"Intake", output:"Output", net:"Net balance", urine:"Urine output", interpretation:"Guided interpretation", positive:"The balance is positive: intake exceeds output. Correlate with clinical assessment, weight, losses and the care plan.", negative:"The balance is negative: output exceeds intake. Review the trend and correlate with the clinical condition and local protocol.", neutral:"The balance is neutral: intake and output are equal in the recorded period.", export:"Download finished balance", trend:"Balance by time band", demo:"Preview with sample data", safeTitle:"Designed for real nursing workflows", safeText:"Guided fields, visible units, consistency checks and fast shift-handover reading.", guard1:"Auditable calculations", guard2:"No patient data storage", guard3:"Trilingual", note:"Decision-support tool. Verify original data and follow institutional protocols; it does not replace clinical judgment.", error:"I could not recognize the template. Use the official template and keep its sheet names.", uploaded:"File analyzed successfully", records:"records" },
  pt: { navHow:"Como funciona", navBenefits:"Benefícios", navSafety:"Segurança", badge:"Balanço hídrico claro e confiável", titleA:"Menos cálculo.", titleB:"Mais tempo para cuidar.", intro:"Baixe o modelo, registre entradas e saídas e envie-o aqui. O app organiza o balanço, identifica inconsistências e prepara um relatório final.", template:"Baixar modelo Excel", start:"Analisar meu modelo", privacy:"Processamento local · Seus dados não saem deste dispositivo", step:"Fluxo de trabalho", s1:"Baixe", s1d:"Modelo claro, com listas e fórmulas visualmente protegidas.", s2:"Registre", s2d:"Preencha os dados do paciente e cada movimento em mL.", s3:"Analise", s3d:"Envie o arquivo e obtenha totais, tendências e explicações.", upload:"Envie o modelo preenchido", drop:"Arraste seu arquivo Excel aqui", browse:"ou selecione no seu computador", choose:"Selecionar arquivo", only:".xlsx · máximo recomendado 10 MB", ready:"Análise pronta", patient:"Paciente", intake:"Entradas", output:"Saídas", net:"Balanço líquido", urine:"Diurese", interpretation:"Interpretação orientativa", positive:"O balanço é positivo: as entradas superam as saídas. Correlacione com avaliação clínica, peso, perdas e prescrição.", negative:"O balanço é negativo: as saídas superam as entradas. Revise a tendência e correlacione com a condição clínica e o protocolo institucional.", neutral:"O balanço é neutro: entradas e saídas são equivalentes no período registrado.", export:"Baixar balanço finalizado", trend:"Balanço por faixa horária", demo:"Prévia com dados de exemplo", safeTitle:"Feito para o trabalho real de enfermagem", safeText:"Campos guiados, unidades visíveis, controles de consistência e leitura rápida na troca de turno.", guard1:"Cálculos auditáveis", guard2:"Sem armazenamento de pacientes", guard3:"Trilíngue", note:"Ferramenta de apoio. Verifique os dados originais e siga o protocolo institucional; não substitui o julgamento clínico.", error:"Não foi possível reconhecer o modelo. Use o modelo oficial e mantenha os nomes das planilhas.", uploaded:"Arquivo analisado com sucesso", records:"registros" }
};

const demo: Result = { patient:"María P. · HC 004182", date:"2026-08-14", intake:2450, output:1980, balance:470, urine:1.12, records:18, bands:[{label:"07–10",intake:650,output:280,balance:370},{label:"11–14",intake:520,output:420,balance:100},{label:"15–18",intake:490,output:360,balance:130},{label:"19–22",intake:420,output:410,balance:10},{label:"23–02",intake:210,output:270,balance:-60},{label:"03–06",intake:160,output:240,balance:-80}] };

function num(v: unknown) { const n = Number(v); return Number.isFinite(n) ? n : 0; }

export default function Home() {
  const [lang, setLang] = useState<Lang>("es");
  const [result, setResult] = useState<Result>(demo);
  const [fileName, setFileName] = useState("");
  const [error, setError] = useState("");
  const [drag, setDrag] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const t = copy[lang];

  async function analyze(file?: File) {
    if (!file) return;
    setError("");
    try {
      const wb = XLSX.read(await file.arrayBuffer(), { type:"array", cellDates:true });
      const ws = wb.Sheets.Registro;
      if (!ws) throw new Error("missing sheet");
      const rows = XLSX.utils.sheet_to_json<unknown[]>(ws, { header:1, defval:"" });
      const data = rows.slice(10,58);
      let intake=0, output=0, urine=0, records=0;
      const bands = [0,0,0,0,0,0].map((_,i)=>({label:["07–10","11–14","15–18","19–22","23–02","03–06"][i],intake:0,output:0,balance:0}));
      data.forEach((r,i)=>{ const type=String(r[2]||"").trim().toLowerCase(); const category=String(r[3]||"").trim().toLowerCase(); const volume=num(r[6]); if(!volume)return; records++; const band=bands[Math.min(5,Math.floor(i/8))]; if(type.includes("ing")||type.includes("entr")||type.includes("intake")){intake+=volume;band.intake+=volume;} else {output+=volume;band.output+=volume;if(category.includes("diur")||category.includes("urine"))urine+=volume;} });
      bands.forEach(b=>b.balance=b.intake-b.output);
      const weight=num(rows[4]?.[1]);
      setResult({patient:`${rows[2]?.[1]||"—"}${rows[2]?.[3]?` · HC ${rows[2][3]}`:""}`,date: rows[2]?.[5] ? String(rows[2][5]).slice(0,10):"—",intake,output,balance:intake-output,urine:weight?urine/weight/24:0,records,bands});
      setFileName(file.name);
      setTimeout(()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth"}),100);
    } catch { setError(t.error); }
  }

  function exportReport() {
    const rows = [["BALANCE HÍDRICO · INFORME FINAL"],["Paciente",result.patient],["Fecha",result.date],["Ingresos (mL)",result.intake],["Egresos (mL)",result.output],["Balance neto (mL)",result.balance],["Diuresis (mL/kg/h)",result.urine],["Registros",result.records],[],["Franja","Ingresos","Egresos","Balance"],...result.bands.map(b=>[b.label,b.intake,b.output,b.balance]),[],[t.interpretation,result.balance>0?t.positive:result.balance<0?t.negative:t.neutral],["Nota",t.note]];
    const ws=XLSX.utils.aoa_to_sheet(rows); ws["!cols"]=[{wch:26},{wch:76},{wch:16},{wch:16}];
    const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,"Informe APP");
    XLSX.writeFile(wb,`Balance_Hidrico_${result.date||"final"}.xlsx`);
  }

  const max = Math.max(...result.bands.flatMap(b=>[b.intake,b.output]),1);
  return <main>
    <header className="topbar"><a className="brand" href="#"><span className="brandMark"><Activity size={20}/></span><span>Balance<span>Care</span></span></a><nav><a href="#flujo">{t.navHow}</a><a href="#beneficios">{t.navBenefits}</a><a href="#seguridad">{t.navSafety}</a></nav><div className="lang"><Languages size={16}/>{(["es","en","pt"] as Lang[]).map(l=><button className={lang===l?"active":""} onClick={()=>setLang(l)} key={l}>{l.toUpperCase()}</button>)}</div></header>

    <section className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/>{t.badge}</div><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p>{t.intro}</p><div className="heroActions"><a className="primary" href="/Plantilla_Balance_Hidrico_Enfermeria.xlsx" download><Download size={19}/>{t.template}</a><button className="secondary" onClick={()=>document.getElementById("upload")?.scrollIntoView({behavior:"smooth"})}>{t.start}<ChevronRight size={18}/></button></div><span className="privacy"><LockKeyhole size={14}/>{t.privacy}</span></div><div className="heroVisual" aria-label={t.demo}><div className="sheetCard"><div className="sheetTop"><div><small>BALANCE · 24H</small><strong>María P.</strong></div><span>14 AGO</span></div><div className="balanceOrb"><small>{t.net}</small><b>+470</b><span>mL</span></div><div className="miniStats"><span><i className="dot in"/>{t.intake}<b>2,450 mL</b></span><span><i className="dot out"/>{t.output}<b>1,980 mL</b></span></div><div className="miniChart">{demo.bands.map((b,i)=><span key={i} style={{height:`${22+Math.abs(b.balance)/3}px`}} className={b.balance<0?"neg":""}/>)}</div><div className="verified"><Check size={14}/> Cálculos verificados</div></div><div className="floatCard"><FileSpreadsheet size={18}/><span>Plantilla inteligente<strong>48 registros</strong></span></div></div></section>

    <section className="workflow" id="flujo"><div className="sectionIntro"><span>01</span><div><small>{t.step}</small><h2>De la hoja al informe, en tres pasos.</h2></div></div><div className="steps">{[[t.s1,t.s1d,Download],[t.s2,t.s2d,FileSpreadsheet],[t.s3,t.s3d,Sparkles]].map(([a,b,Icon],i)=><article key={String(a)}><div className="stepIcon"><Icon size={23}/><span>0{i+1}</span></div><h3>{String(a)}</h3><p>{String(b)}</p></article>)}</div></section>

    <section className="analyzer" id="upload"><div className="analyzerHead"><span>02 · ANALIZADOR</span><h2>{t.upload}</h2><p>{t.privacy}</p></div><div className={`dropzone ${drag?"drag":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);analyze(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><input ref={input} type="file" accept=".xlsx,.xls" onChange={e=>analyze(e.target.files?.[0])}/><div className="uploadIcon"><UploadCloud size={30}/></div><h3>{t.drop}</h3><p>{t.browse}</p><button>{t.choose}</button><small>{t.only}</small></div>{error&&<p className="error">{error}</p>}{fileName&&<p className="success"><Check size={15}/>{t.uploaded}: {fileName}</p>}</section>

    <section className="results" id="results"><div className="resultsTop"><div><span>03 · {t.ready.toUpperCase()}</span><h2>{t.ready}</h2><p>{t.patient}: <strong>{result.patient}</strong> · {result.date} · {result.records} {t.records}</p></div><button className="primary" onClick={exportReport}><ArrowDownToLine size={18}/>{t.export}</button></div><div className="kpis"><article><small>{t.intake}</small><b>{result.intake.toLocaleString()} <i>mL</i></b><span className="up">↑ total</span></article><article><small>{t.output}</small><b>{result.output.toLocaleString()} <i>mL</i></b><span className="down">↓ total</span></article><article className={result.balance<0?"negative":"accent"}><small>{t.net}</small><b>{result.balance>0?"+":""}{result.balance.toLocaleString()} <i>mL</i></b><span>24 h</span></article><article><small>{t.urine}</small><b>{result.urine.toFixed(2)} <i>mL/kg/h</i></b><span>calculado</span></article></div><div className="analysisGrid"><article className="chartCard"><div className="cardTitle"><div><small>{t.trend}</small><h3>{t.intake} vs. {t.output}</h3></div><div className="legend"><span><i className="in"/> {t.intake}</span><span><i className="out"/> {t.output}</span></div></div><div className="barChart">{result.bands.map((b,i)=><div className="barGroup" key={i}><div className="bars"><span className="bar in" style={{height:`${Math.max(3,b.intake/max*150)}px`}}/><span className="bar out" style={{height:`${Math.max(3,b.output/max*150)}px`}}/></div><small>{b.label}</small></div>)}</div></article><article className="explainCard"><span className="explainIcon"><Sparkles size={19}/></span><small>{t.interpretation}</small><h3>{result.balance>0?"Balance positivo":result.balance<0?"Balance negativo":"Balance neutro"}</h3><p>{result.balance>0?t.positive:result.balance<0?t.negative:t.neutral}</p><div><ShieldCheck size={16}/>{t.note}</div></article></div></section>

    <section className="safety" id="seguridad"><div><span id="beneficios">04 · CONFIANZA</span><h2>{t.safeTitle}</h2><p>{t.safeText}</p></div><div className="guards"><span><Check/> {t.guard1}</span><span><LockKeyhole/> {t.guard2}</span><span><Languages/> {t.guard3}</span></div></section>
    <footer><div className="brand"><span className="brandMark"><Activity size={18}/></span><span>Balance<span>Care</span></span></div><p>{t.note}</p><small>Versión clínica inicial · 2026</small></footer>
  </main>;
}
