"use client";

import { useRef, useState } from "react";
import * as XLSX from "xlsx";
import { Activity, ArrowDownToLine, BookOpen, Check, ChevronRight, Database, Download, FileSpreadsheet, Languages, LockKeyhole, RefreshCw, ShieldCheck, Sparkles, Trash2, UploadCloud } from "lucide-react";

type Lang = "es" | "en" | "zh" | "pt";
type Result = { patient: string; date: string; intake: number; output: number; balance: number; urine: number; records: number; bands: { label: string; intake: number; output: number; balance: number }[] };
type Day = { id:number; admissionId:string; patientLabel:string; balanceDate:string; intakeMl:number; outputMl:number; balanceMl:number; urineMlKgH:number; recordCount:number };

const copy = {
  es: { navHow:"Cómo funciona", navBenefits:"Beneficios", navSafety:"Seguridad", badge:"Balance hídrico, claro y confiable", titleA:"Menos cálculo.", titleB:"Más tiempo para cuidar.", intro:"Descarga la plantilla, registra ingresos y egresos y súbela aquí. La app organiza el balance, detecta inconsistencias y prepara un informe listo para descargar.", template:"Descargar plantilla Excel", start:"Analizar mi plantilla", privacy:"Procesamiento local · Tus datos no salen de este dispositivo", step:"Flujo de trabajo", s1:"Descarga", s1d:"Plantilla clara, con listas y fórmulas protegidas visualmente.", s2:"Registra", s2d:"Completa los datos del paciente y cada movimiento en mL.", s3:"Analiza", s3d:"Sube el archivo y obtén totales, tendencias y explicaciones.", upload:"Sube la plantilla completada", drop:"Arrastra tu archivo Excel aquí", browse:"o selecciónalo desde tu equipo", choose:"Seleccionar archivo", only:".xlsx · máximo recomendado 10 MB", ready:"Análisis listo", patient:"Paciente", intake:"Ingresos", output:"Egresos", net:"Balance neto", urine:"Diuresis", interpretation:"Interpretación orientativa", positive:"El balance es positivo: los ingresos superan los egresos. Correlaciona este resultado con la valoración clínica, el peso, las pérdidas y la prescripción.", negative:"El balance es negativo: los egresos superan los ingresos. Revisa la tendencia y correlaciona con el estado clínico y el protocolo institucional.", neutral:"El balance es neutro: ingresos y egresos son equivalentes en el período registrado.", export:"Descargar balance terminado", trend:"Balance por franja horaria", demo:"Vista previa con datos de ejemplo", safeTitle:"Diseñada para el trabajo real de enfermería", safeText:"Campos guiados, unidades visibles, controles de consistencia y una lectura rápida para el cambio de turno.", guard1:"Cálculos auditables", guard2:"Historial privado protegido", guard3:"Cuatro idiomas", note:"Herramienta de apoyo. Verifica los datos originales y sigue el protocolo institucional; no sustituye el juicio clínico.", error:"No pude reconocer la plantilla. Usa la plantilla oficial y conserva los nombres de sus hojas.", uploaded:"Archivo analizado correctamente", records:"registros" },
  en: { navHow:"How it works", navBenefits:"Benefits", navSafety:"Safety", badge:"Clear, reliable fluid balance", titleA:"Less calculation.", titleB:"More time to care.", intro:"Download the template, record intake and output, then upload it here. The app organizes the balance, detects inconsistencies and prepares a finished report.", template:"Download Excel template", start:"Analyze my template", privacy:"Local processing · Your data never leaves this device", step:"Workflow", s1:"Download", s1d:"A clear template with lists and visually protected formulas.", s2:"Record", s2d:"Complete patient data and every movement in mL.", s3:"Analyze", s3d:"Upload the file for totals, trends and clear explanations.", upload:"Upload the completed template", drop:"Drop your Excel file here", browse:"or select it from your computer", choose:"Choose file", only:".xlsx · recommended maximum 10 MB", ready:"Analysis ready", patient:"Patient", intake:"Intake", output:"Output", net:"Net balance", urine:"Urine output", interpretation:"Guided interpretation", positive:"The balance is positive: intake exceeds output. Correlate with clinical assessment, weight, losses and the care plan.", negative:"The balance is negative: output exceeds intake. Review the trend and correlate with the clinical condition and local protocol.", neutral:"The balance is neutral: intake and output are equal in the recorded period.", export:"Download finished balance", trend:"Balance by time band", demo:"Preview with sample data", safeTitle:"Designed for real nursing workflows", safeText:"Guided fields, visible units, consistency checks and fast shift-handover reading.", guard1:"Auditable calculations", guard2:"Protected private history", guard3:"Four languages", note:"Decision-support tool. Verify original data and follow institutional protocols; it does not replace clinical judgment.", error:"I could not recognize the template. Use the official template and keep its sheet names.", uploaded:"File analyzed successfully", records:"records" },
  pt: { navHow:"Como funciona", navBenefits:"Benefícios", navSafety:"Segurança", badge:"Balanço hídrico claro e confiável", titleA:"Menos cálculo.", titleB:"Mais tempo para cuidar.", intro:"Baixe o modelo, registre entradas e saídas e envie-o aqui. O app organiza o balanço, identifica inconsistências e prepara um relatório final.", template:"Baixar modelo Excel", start:"Analisar meu modelo", privacy:"Processamento local · Seus dados não saem deste dispositivo", step:"Fluxo de trabalho", s1:"Baixe", s1d:"Modelo claro, com listas e fórmulas visualmente protegidas.", s2:"Registre", s2d:"Preencha os dados do paciente e cada movimento em mL.", s3:"Analise", s3d:"Envie o arquivo e obtenha totais, tendências e explicações.", upload:"Envie o modelo preenchido", drop:"Arraste seu arquivo Excel aqui", browse:"ou selecione no seu computador", choose:"Selecionar arquivo", only:".xlsx · máximo recomendado 10 MB", ready:"Análise pronta", patient:"Paciente", intake:"Entradas", output:"Saídas", net:"Balanço líquido", urine:"Diurese", interpretation:"Interpretação orientativa", positive:"O balanço é positivo: as entradas superam as saídas. Correlacione com avaliação clínica, peso, perdas e prescrição.", negative:"O balanço é negativo: as saídas superam as entradas. Revise a tendência e correlacione com a condição clínica e o protocolo institucional.", neutral:"O balanço é neutro: entradas e saídas são equivalentes no período registrado.", export:"Baixar balanço finalizado", trend:"Balanço por faixa horária", demo:"Prévia com dados de exemplo", safeTitle:"Feito para o trabalho real de enfermagem", safeText:"Campos guiados, unidades visíveis, controles de consistência e leitura rápida na troca de turno.", guard1:"Cálculos auditáveis", guard2:"Sem armazenamento de pacientes", guard3:"Trilíngue", note:"Ferramenta de apoio. Verifique os dados originais e siga o protocolo institucional; não substitui o julgamento clínico.", error:"Não foi possível reconhecer o modelo. Use o modelo oficial e mantenha os nomes das planilhas.", uploaded:"Arquivo analisado com sucesso", records:"registros" }
,
  zh: { navHow:"使用方法", navBenefits:"优势", navSafety:"安全", badge:"清晰、可靠的液体平衡", titleA:"减少计算。", titleB:"把更多时间用于护理。", intro:"下载模板，记录液体摄入和排出，然后上传。应用会整理液体平衡、检查不一致并生成可下载的完整报告。", template:"下载 Excel 模板", start:"分析我的模板", privacy:"本地处理 · 上传分析时文件不会离开此设备", step:"工作流程", s1:"下载", s1d:"清晰的模板，包含下拉选项和可识别的公式单元格。", s2:"记录", s2d:"填写患者资料，并以 mL 记录每次摄入或排出。", s3:"分析", s3d:"上传文件，查看总量、趋势和解释。", upload:"上传已填写的模板", drop:"将 Excel 文件拖到这里", browse:"或从电脑中选择", choose:"选择文件", only:".xlsx · 建议不超过 10 MB", ready:"分析完成", patient:"患者", intake:"摄入量", output:"排出量", net:"净平衡", urine:"尿量", interpretation:"参考解释", positive:"液体平衡为正：摄入量大于排出量。请结合临床评估、体重、额外丢失和医嘱进行判断。", negative:"液体平衡为负：排出量大于摄入量。请查看趋势，并结合患者临床状况和机构规范进行判断。", neutral:"液体平衡为零：记录时段内摄入量与排出量相等。", export:"下载完整液体平衡", trend:"按时间段显示液体平衡", demo:"示例数据预览", safeTitle:"专为真实护理工作流程设计", safeText:"引导式字段、明确单位、一致性检查和便于交班的快速阅读。", guard1:"可审核的计算", guard2:"按用户保护的住院记录", guard3:"四种语言", note:"本工具仅用于辅助。请核对原始数据并遵循机构规范；不能替代临床判断。", error:"无法识别该模板。请使用官方模板并保留工作表名称。", uploaded:"文件分析成功", records:"条记录" }
};

const extra = {
  es:{history:"BH acumulado por hospitalización",historyText:"Guarda cada balance diario bajo un código de hospitalización y consolida toda la estancia.",admission:"Código de hospitalización / episodio",load:"Consultar historial",add:"Agregar o actualizar este día",days:"Días registrados",cumulative:"BH acumulado",empty:"Aún no hay balances guardados para este episodio.",saved:"Día guardado en el historial",formulaTitle:"Cómo se calculan los resultados",formulaText:"Cada resultado conserva una fórmula simple, su unidad y el contexto necesario para interpretarlo.",f1:"Ingresos totales = suma de volúmenes clasificados como ingreso.",f2:"Egresos totales = suma de volúmenes clasificados como egreso.",f3:"Balance neto = ingresos totales − egresos totales.",f4:"Diuresis = diuresis total ÷ peso (kg) ÷ horas observadas.",f5:"BH acumulado = suma progresiva de los balances diarios.",bibliography:"Bibliografía sustentatoria",scope:"Los umbrales no constituyen diagnóstico. La interpretación depende de edad, diagnóstico, función renal, examen, peso, laboratorio y protocolo institucional.",privateHistory:"Historial privado vinculado al usuario autenticado."},
  en:{history:"Cumulative fluid balance by hospitalization",historyText:"Save each daily balance under an admission code and consolidate the full stay.",admission:"Admission / episode code",load:"Load history",add:"Add or update this day",days:"Recorded days",cumulative:"Cumulative balance",empty:"No balances have been saved for this episode yet.",saved:"Day saved to history",formulaTitle:"How results are calculated",formulaText:"Every result keeps a simple formula, its unit and the context needed for interpretation.",f1:"Total intake = sum of volumes classified as intake.",f2:"Total output = sum of volumes classified as output.",f3:"Net balance = total intake − total output.",f4:"Urine output = total urine ÷ weight (kg) ÷ observed hours.",f5:"Cumulative balance = running sum of daily balances.",bibliography:"Supporting bibliography",scope:"Thresholds are not a diagnosis. Interpretation depends on age, diagnosis, renal function, examination, weight, laboratory results and institutional protocol.",privateHistory:"Private history linked to the authenticated user."},
  zh:{history:"住院期间累计液体平衡",historyText:"使用住院编号保存每日液体平衡，并汇总整个住院期间的数据。",admission:"住院 / 就诊编号",load:"查询历史",add:"添加或更新当天记录",days:"已记录天数",cumulative:"累计液体平衡",empty:"该住院编号尚无保存的记录。",saved:"当天记录已保存",formulaTitle:"结果如何计算",formulaText:"每项结果均保留简单公式、单位及解释所需的临床背景。",f1:"总摄入量 = 所有归类为摄入的液体体积之和。",f2:"总排出量 = 所有归类为排出的液体体积之和。",f3:"净平衡 = 总摄入量 − 总排出量。",f4:"每小时每公斤尿量 = 总尿量 ÷ 体重(kg) ÷ 观察小时数。",f5:"累计液体平衡 = 每日净平衡的连续累加。",bibliography:"支持性参考文献",scope:"阈值不能单独用于诊断。解释应结合年龄、诊断、肾功能、体格检查、体重、实验室结果及机构规范。",privateHistory:"历史记录与已认证用户关联并保持私密。"},
  pt:{history:"Balanço hídrico acumulado por internação",historyText:"Salve cada balanço diário sob um código de internação e consolide toda a permanência.",admission:"Código da internação / episódio",load:"Consultar histórico",add:"Adicionar ou atualizar este dia",days:"Dias registrados",cumulative:"BH acumulado",empty:"Ainda não há balanços salvos para este episódio.",saved:"Dia salvo no histórico",formulaTitle:"Como os resultados são calculados",formulaText:"Cada resultado mantém uma fórmula simples, sua unidade e o contexto necessário para interpretação.",f1:"Entradas totais = soma dos volumes classificados como entrada.",f2:"Saídas totais = soma dos volumes classificados como saída.",f3:"Balanço líquido = entradas totais − saídas totais.",f4:"Diurese = diurese total ÷ peso (kg) ÷ horas observadas.",f5:"BH acumulado = soma progressiva dos balanços diários.",bibliography:"Bibliografia de apoio",scope:"Os limites não constituem diagnóstico. A interpretação depende de idade, diagnóstico, função renal, exame, peso, laboratório e protocolo institucional.",privateHistory:"Histórico privado vinculado ao usuário autenticado."}
};

const demo: Result = { patient:"María P. · HC 004182", date:"2026-08-14", intake:2450, output:1980, balance:470, urine:1.12, records:18, bands:[{label:"07–10",intake:650,output:280,balance:370},{label:"11–14",intake:520,output:420,balance:100},{label:"15–18",intake:490,output:360,balance:130},{label:"19–22",intake:420,output:410,balance:10},{label:"23–02",intake:210,output:270,balance:-60},{label:"03–06",intake:160,output:240,balance:-80}] };

function num(v: unknown) { const n = Number(v); return Number.isFinite(n) ? n : 0; }

export default function Home() {
  const [lang, setLang] = useState<Lang>("es");
  const [result, setResult] = useState<Result>(demo);
  const [fileName, setFileName] = useState("");
  const [error, setError] = useState("");
  const [drag, setDrag] = useState(false);
  const [admissionId, setAdmissionId] = useState("HC-004182");
  const [days, setDays] = useState<Day[]>([]);
  const [historyMessage, setHistoryMessage] = useState("");
  const input = useRef<HTMLInputElement>(null);
  const t = copy[lang];
  const e = extra[lang];

  async function loadHistory() {
    if (!admissionId.trim()) return;
    setHistoryMessage("");
    const response = await fetch(`/api/balances?admissionId=${encodeURIComponent(admissionId.trim())}`);
    if (!response.ok) { setHistoryMessage("No se pudo consultar el historial."); return; }
    const data = await response.json() as { days: Day[] };
    setDays(data.days);
  }

  async function saveDay() {
    if (!admissionId.trim() || !fileName || !/^\d{4}-\d{2}-\d{2}$/.test(result.date)) return;
    const response = await fetch("/api/balances", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({admissionId:admissionId.trim(),patientLabel:result.patient,balanceDate:result.date,intakeMl:result.intake,outputMl:result.output,balanceMl:result.balance,urineMlKgH:result.urine,recordCount:result.records}) });
    if (response.ok) { setHistoryMessage(e.saved); await loadHistory(); }
  }

  async function deleteDay(id:number) {
    const response = await fetch("/api/balances", { method:"DELETE", headers:{"content-type":"application/json"}, body:JSON.stringify({id}) });
    if (response.ok) await loadHistory();
  }

  async function analyze(file?: File) {
    if (!file) return;
    setError("");
    try {
      const wb = XLSX.read(await file.arrayBuffer(), { type:"array", cellDates:true });
      const ws = wb.Sheets.Registro;
      if (!ws) throw new Error("missing sheet");
      const rows = XLSX.utils.sheet_to_json<unknown[]>(ws, { header:1, defval:"" });
      const data = rows.slice(10,58);
      let intake=0, output=0, urine=0, records=0;
      const bands = [0,0,0,0,0,0].map((_,i)=>({label:["07–10","11–14","15–18","19–22","23–02","03–06"][i],intake:0,output:0,balance:0}));
      data.forEach((r,i)=>{ const type=String(r[2]||"").trim().toLowerCase(); const category=String(r[3]||"").trim().toLowerCase(); const volume=num(r[6]); if(!volume)return; records++; const band=bands[Math.min(5,Math.floor(i/8))]; if(type.includes("ing")||type.includes("entr")||type.includes("intake")){intake+=volume;band.intake+=volume;} else {output+=volume;band.output+=volume;if(category.includes("diur")||category.includes("urine"))urine+=volume;} });
      bands.forEach(b=>b.balance=b.intake-b.output);
      const weight=num(rows[4]?.[1]);
      setResult({patient:`${rows[2]?.[1]||"—"}${rows[2]?.[3]?` · HC ${rows[2][3]}`:""}`,date: rows[2]?.[5] ? String(rows[2][5]).slice(0,10):"—",intake,output,balance:intake-output,urine:weight?urine/weight/24:0,records,bands});
      setFileName(file.name);
      setTimeout(()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth"}),100);
    } catch { setError(t.error); }
  }

  function exportReport() {
    const rows = [["BALANCE HÍDRICO · INFORME FINAL"],["Paciente",result.patient],["Fecha",result.date],["Ingresos (mL)",result.intake],["Egresos (mL)",result.output],["Balance neto (mL)",result.balance],["Diuresis (mL/kg/h)",result.urine],["Registros",result.records],[],["Franja","Ingresos","Egresos","Balance"],...result.bands.map(b=>[b.label,b.intake,b.output,b.balance]),[],[t.interpretation,result.balance>0?t.positive:result.balance<0?t.negative:t.neutral],["Nota",t.note]];
    const ws=XLSX.utils.aoa_to_sheet(rows); ws["!cols"]=[{wch:26},{wch:76},{wch:16},{wch:16}];
    const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,"Informe APP");
    XLSX.writeFile(wb,`Balance_Hidrico_${result.date||"final"}.xlsx`);
  }

  const max = Math.max(...result.bands.flatMap(b=>[b.intake,b.output]),1);
  return <main>
    <header className="topbar"><a className="brand" href="#"><span className="brandMark"><Activity size={20}/></span><span>AME Balance <span>Care</span></span></a><nav><a href="#flujo">{t.navHow}</a><a href="#acumulado">{e.cumulative}</a><a href="#bibliografia">{e.bibliography}</a><a href="#seguridad">{t.navSafety}</a></nav><div className="lang"><Languages size={16}/>{(["es","en","zh","pt"] as Lang[]).map(l=><button className={lang===l?"active":""} onClick={()=>setLang(l)} key={l}>{l==="zh"?"中文":l.toUpperCase()}</button>)}</div></header>

    <section className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/>{t.badge}</div><h1>{t.titleA}<br/><em>{t.titleB}</em></h1><p>{t.intro}</p><div className="heroActions"><a className="primary" href="/Plantilla_Balance_Hidrico_Enfermeria.xlsx" download><Download size={19}/>{t.template}</a><button className="secondary" onClick={()=>document.getElementById("upload")?.scrollIntoView({behavior:"smooth"})}>{t.start}<ChevronRight size={18}/></button></div><span className="privacy"><LockKeyhole size={14}/>{t.privacy}</span></div><div className="heroVisual" aria-label={t.demo}><div className="sheetCard"><div className="sheetTop"><div><small>BALANCE · 24H</small><strong>María P.</strong></div><span>14 AGO</span></div><div className="balanceOrb"><small>{t.net}</small><b>+470</b><span>mL</span></div><div className="miniStats"><span><i className="dot in"/>{t.intake}<b>2,450 mL</b></span><span><i className="dot out"/>{t.output}<b>1,980 mL</b></span></div><div className="miniChart">{demo.bands.map((b,i)=><span key={i} style={{height:`${22+Math.abs(b.balance)/3}px`}} className={b.balance<0?"neg":""}/>)}</div><div className="verified"><Check size={14}/> Cálculos verificados</div></div><div className="floatCard"><FileSpreadsheet size={18}/><span>Plantilla inteligente<strong>48 registros</strong></span></div></div></section>

    <section className="workflow" id="flujo"><div className="sectionIntro"><span>01</span><div><small>{t.step}</small><h2>De la hoja al informe, en tres pasos.</h2></div></div><div className="steps">{[[t.s1,t.s1d,Download],[t.s2,t.s2d,FileSpreadsheet],[t.s3,t.s3d,Sparkles]].map(([a,b,Icon],i)=><article key={String(a)}><div className="stepIcon"><Icon size={23}/><span>0{i+1}</span></div><h3>{String(a)}</h3><p>{String(b)}</p></article>)}</div></section>

    <section className="analyzer" id="upload"><div className="analyzerHead"><span>02 · ANALIZADOR</span><h2>{t.upload}</h2><p>{t.privacy}</p></div><div className={`dropzone ${drag?"drag":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);analyze(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><input ref={input} type="file" accept=".xlsx,.xls" onChange={e=>analyze(e.target.files?.[0])}/><div className="uploadIcon"><UploadCloud size={30}/></div><h3>{t.drop}</h3><p>{t.browse}</p><button>{t.choose}</button><small>{t.only}</small></div>{error&&<p className="error">{error}</p>}{fileName&&<p className="success"><Check size={15}/>{t.uploaded}: {fileName}</p>}</section>

    <section className="results" id="results"><div className="resultsTop"><div><span>03 · {t.ready.toUpperCase()}</span><h2>{t.ready}</h2><p>{t.patient}: <strong>{result.patient}</strong> · {result.date} · {result.records} {t.records}</p></div><button className="primary" onClick={exportReport}><ArrowDownToLine size={18}/>{t.export}</button></div><div className="kpis"><article><small>{t.intake}</small><b>{result.intake.toLocaleString()} <i>mL</i></b><span className="up">↑ total</span></article><article><small>{t.output}</small><b>{result.output.toLocaleString()} <i>mL</i></b><span className="down">↓ total</span></article><article className={result.balance<0?"negative":"accent"}><small>{t.net}</small><b>{result.balance>0?"+":""}{result.balance.toLocaleString()} <i>mL</i></b><span>24 h</span></article><article><small>{t.urine}</small><b>{result.urine.toFixed(2)} <i>mL/kg/h</i></b><span>calculado</span></article></div><div className="analysisGrid"><article className="chartCard"><div className="cardTitle"><div><small>{t.trend}</small><h3>{t.intake} vs. {t.output}</h3></div><div className="legend"><span><i className="in"/> {t.intake}</span><span><i className="out"/> {t.output}</span></div></div><div className="barChart">{result.bands.map((b,i)=><div className="barGroup" key={i}><div className="bars"><span className="bar in" style={{height:`${Math.max(3,b.intake/max*150)}px`}}/><span className="bar out" style={{height:`${Math.max(3,b.output/max*150)}px`}}/></div><small>{b.label}</small></div>)}</div></article><article className="explainCard"><span className="explainIcon"><Sparkles size={19}/></span><small>{t.interpretation}</small><h3>{result.balance>0?"Balance positivo":result.balance<0?"Balance negativo":"Balance neutro"}</h3><p>{result.balance>0?t.positive:result.balance<0?t.negative:t.neutral}</p><div><ShieldCheck size={16}/>{t.note}</div></article></div></section>

    <section className="historySection" id="acumulado"><div className="historyHead"><div><span>04 · HISTORIAL</span><h2>{e.history}</h2><p>{e.historyText}</p></div><Database size={42}/></div><div className="historyControls"><label><span>{e.admission}</span><input value={admissionId} onChange={event=>setAdmissionId(event.target.value)} placeholder="Ej. HC-004182-2026"/></label><button className="secondary" onClick={loadHistory}><RefreshCw size={17}/>{e.load}</button><button className="primary" onClick={saveDay} disabled={!fileName}><Check size={17}/>{e.add}</button></div><p className="historyPrivacy"><LockKeyhole size={14}/>{e.privateHistory}</p>{historyMessage&&<p className="success dark"><Check size={15}/>{historyMessage}</p>}<div className="historySummary"><article><small>{e.days}</small><b>{days.length}</b></article><article><small>{e.cumulative}</small><b>{days.reduce((sum,day)=>sum+day.balanceMl,0).toLocaleString()} <i>mL</i></b></article></div>{days.length===0?<div className="emptyHistory">{e.empty}</div>:<div className="historyTableWrap"><table><thead><tr><th>Fecha</th><th>{t.patient}</th><th>{t.intake}</th><th>{t.output}</th><th>{t.net}</th><th>{e.cumulative}</th><th/></tr></thead><tbody>{days.map((day,index)=>{const accumulated=days.slice(0,index+1).reduce((sum,item)=>sum+item.balanceMl,0);return <tr key={day.id}><td>{day.balanceDate}</td><td>{day.patientLabel}</td><td>{day.intakeMl.toLocaleString()} mL</td><td>{day.outputMl.toLocaleString()} mL</td><td className={day.balanceMl<0?"valueNeg":"valuePos"}>{day.balanceMl>0?"+":""}{day.balanceMl.toLocaleString()} mL</td><td><strong>{accumulated>0?"+":""}{accumulated.toLocaleString()} mL</strong></td><td><button className="iconButton" onClick={()=>deleteDay(day.id)} aria-label="Eliminar día"><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>}</section>

    <section className="evidence" id="bibliografia"><div className="evidenceIntro"><span>05 · EVIDENCIA</span><h2>{e.formulaTitle}</h2><p>{e.formulaText}</p></div><div className="formulaGrid">{[e.f1,e.f2,e.f3,e.f4,e.f5].map((formula,index)=><article key={formula}><span>0{index+1}</span><p>{formula}</p></article>)}</div><div className="sources"><div><BookOpen size={24}/><h3>{e.bibliography}</h3><p>{e.scope}</p></div><ol><li><a href="https://www.nice.org.uk/guidance/cg174" target="_blank" rel="noreferrer">NICE CG174 · Intravenous fluid therapy in adults in hospital</a><small>Evaluación, plan de 24 horas, monitorización y reevaluación clínica.</small></li><li><a href="https://www.nice.org.uk/guidance/ng29/chapter/recommendations" target="_blank" rel="noreferrer">NICE NG29 · Intravenous fluid therapy in children and young people</a><small>Registro horario de tipos y volúmenes, con totales continuos.</small></li><li><a href="https://www.nice.org.uk/guidance/ng148/chapter/Recommendations" target="_blank" rel="noreferrer">NICE NG148 · Acute kidney injury</a><small>Reconocimiento de oliguria y necesidad de respuesta clínica contextual.</small></li></ol></div></section>

    <section className="safety" id="seguridad"><div><span id="beneficios">06 · CONFIANZA</span><h2>{t.safeTitle}</h2><p>{t.safeText}</p></div><div className="guards"><span><Check/> {t.guard1}</span><span><LockKeyhole/> {t.guard2}</span><span><Languages/> {t.guard3}</span></div></section>
    <footer><div className="brand"><span className="brandMark"><Activity size={18}/></span><span>AME Balance <span>Care</span></span></div><p>{t.note}</p><small>Versión clínica inicial · 2026</small></footer>
  </main>;
}
